
[workspace]
members = [
  "packages/keekijanai-serve-macro",
  "packages/keekijanai-serve-core",
  "packages/keekijanai-serve-rust-server-demo"
]
exclude = [
  "packages/keekijanai-gatsby-vercel-demo/api"
]