version: "3.1"

services:
  keekijanai-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - postgre_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgre_data:
  pgadmin_data:
