[package]
name = "keekijanai-serve-macro"
version = "0.1.0-alpha.0"
edition = "2021"
description = "No description"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["parsing"] }
quote = "1.0"
darling = "0.13.2"