[package]
name = "keekijanai-serve-resp-err-macro"
version = "0.1.0-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
keekijanai-serve-resp-err = { path = "../keekijanai-serve-resp-err" }