[package]
name = "keekijanai-serve-vercel-adapter"
version = "0.1.0-alpha.2"
edition = "2021"
description = "No description"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.1"
vercel_lambda = "0.2.0"
tokio = { version = "1", features = ["full"] }
keekijanai-serve-core = { version = "0.1.0-alpha.2", path = "../keekijanai-serve-core" }
querystring = "1.1.0"
urlencoding = "2.1.0"
tracing-subscriber = "0.2"